openapi: 3.0.3
info:
  title: Job Aggregator Monetization & LLM API
  version: 1.0.0
  description: APIs for subscriptions, payments, LLM assistants, and notifications.
servers:
  - url: https://api.example.com/api/v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SubscriptionPlan:
      type: object
      properties:
        id:
          type: string
          format: uuid
        planType:
          type: string
          enum: [Employer, Candidate]
        name:
          type: string
        description:
          type: string
        pricePerMonth:
          type: number
          format: float
        pricePerYear:
          type: number
          format: float
          nullable: true
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        planId:
          type: string
          format: uuid
        status:
          type: string
          enum: [Trial, Active, Suspended, Cancelled, Expired]
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
    LlmSession:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [EmployerAssistant, CandidateAssistant]
        startedAt:
          type: string
          format: date-time
        endedAt:
          type: string
          format: date-time
          nullable: true
    LlmMessage:
      type: object
      properties:
        id:
          type: string
          format: uuid
        senderType:
          type: string
          enum: [User, Assistant]
        text:
          type: string
        sentAt:
          type: string
          format: date-time
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        body:
          type: string
        channel:
          type: string
          enum: [Email, InApp, Push]
        isRead:
          type: boolean
        sentAt:
          type: string
          format: date-time
paths:
  /subscriptions/plans:
    get:
      summary: List subscription plans
      tags: [Subscriptions]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionPlan'
  /companies/{id}/subscriptions:
    post:
      summary: Create or upgrade employer subscription
      tags: [Subscriptions]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [planId]
              properties:
                planId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
  /companies/{id}/subscriptions/current:
    get:
      summary: Get current employer subscription
      tags: [Subscriptions]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Current subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
  /candidates/me/subscriptions:
    post:
      summary: Create candidate subscription
      tags: [Subscriptions]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [planId]
              properties:
                planId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
    get:
      summary: List candidate subscriptions
      tags: [Subscriptions]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
  /payments/checkout-session:
    post:
      summary: Create checkout session
      tags: [Payments]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [planId]
              properties:
                planId:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Checkout session created
  /llm/employer/sessions:
    post:
      summary: Start employer LLM session
      tags: [LLM]
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmSession'
  /llm/employer/sessions/{id}/messages:
    post:
      summary: Send message in employer LLM session
      tags: [LLM]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Assistant reply
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    $ref: '#/components/schemas/LlmSession'
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/LlmMessage'
  /llm/candidate/sessions:
    post:
      summary: Start candidate LLM session
      tags: [LLM]
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmSession'
  /llm/candidate/sessions/{id}/messages:
    post:
      summary: Send message in candidate LLM session
      tags: [LLM]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Assistant reply
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    $ref: '#/components/schemas/LlmSession'
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/LlmMessage'
  /notifications:
    get:
      summary: List notifications for current user
      tags: [Notifications]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
  /notifications/{id}/read:
    patch:
      summary: Mark notification as read
      tags: [Notifications]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Marked as read


